blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'

urlpatterns = [
    path('', views.post_list , name='post_list'),
    path('<int:id>' , views.post_detail , name='post_detail'),
    path('tags=<slug:tag>' , views.post_by_tag , name='post_by_tag'),
    path('category=<slug:category>' , views.post_by_category , name='post_by_category'),
]

home/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home , name='home'),
]

kingdomblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/' , include('blog.urls' , namespace='blog')),
    path('' , include('home.urls' , namespace='home')),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


admin.site.site_header = "Divine Montessori AdminPanel"
admin.site.site_title = "Divine Montessori App Admin"
admin.site.site_index_title = "Welcome To Divine Montessori Admin Panel"

blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from taggit.managers import TaggableManager



# Create your models here.

class Post(models.Model):
    title = models.CharField(max_length=50)
    image = models.ImageField(upload_to='blog/' , blank=True, null=True)
    content = models.TextField()
    author = models.ForeignKey(User , on_delete=models.CASCADE)
    # tags
    category = models.ForeignKey('Category' ,null=True, on_delete=models.SET_NULL)
    created = models.DateTimeField(default=timezone.now)

    tags = TaggableManager(blank=True)

    class Meta:
        verbose_name = 'post'
        verbose_name_plural = 'posts'


    def __str__(self):
        return self.title

class Category(models.Model):
    category_name = models.CharField(max_length=50)


    class Meta:
        verbose_name = 'category'
        verbose_name_plural = 'categories'


    def __str__(self):
        return self.category_name


class Comment(models.Model):
    user = models.ForeignKey(User , on_delete=models.CASCADE)
    post = models.ForeignKey(Post , on_delete=models.CASCADE)
    content = models.TextField()
    created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return str(self.content)

home/models.py
from django.db import models

# Create your models here.

class AboutUs(models.Model):
    title = models.CharField(max_length=50)
    content = models.TextField()
    number = models.IntegerField()

    class Meta:
        verbose_name = 'about us'
        verbose_name_plural = 'about us'

    def __str__(self):
        return self.title


class Services(models.Model):
    heading = models.CharField(max_length=50)
    title = models.CharField(max_length=50)
    content = models.TextField()
    image = models.ImageField(upload_to='services/')


    class Meta:
        verbose_name = 'services'
        verbose_name_plural = 'services'

    def __str__(self):
        return self.title


class Team(models.Model):
    name = models.CharField(max_length=50)
    title = models.CharField(max_length=50)
    bio = models.TextField()
    image = models.ImageField(upload_to='team/')


    class Meta:
        verbose_name = 'team'
        verbose_name_plural = 'team'

    def __str__(self):
        return self.name

class Testimony(models.Model):
    name = models.CharField(max_length=50)
    title = models.CharField(max_length=50)
    bio = models.TextField()
    image = models.ImageField(upload_to='testimony/')


    class Meta:
        verbose_name = 'testimony'
        verbose_name_plural = 'testimonials'

    def __str__(self):
        return self.name

class Gallery(models.Model): 
    description = models.CharField(max_length=100)
    image_gallery = models.ImageField(upload_to='gallery/')


    class Meta:
        verbose_name = 'gallery'
        verbose_name_plural = 'galleries'

    def __str__(self):
        return self.description

class Application(models.Model): 
    description = models.CharField(max_length=100)
    application_form = models.FileField(upload_to='Application', blank=True)


    class Meta:
        verbose_name = 'Application form'
        verbose_name_plural = 'Application forms'

    def __str__(self):
        return self.description

    

blog/forms.py
from django import forms
from .models import Comment


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [
            'content'
        ]

blog/views.py
from django.shortcuts import render
from .models import Post , Category , Comment
from taggit.models import Tag
from .forms import CommentForm
from django.core.paginator import Paginator
from django.db.models import Q

# Create your views here.

def post_list(request):
    post_list = Post.objects.all().order_by('-created')

    ## Search
    search_query = request.GET.get('q')
    if search_query :
        post_list = post_list.filter(
            Q(title__icontains = search_query) |
            Q(content__icontains = search_query) |
            Q(tags__name__icontains = search_query)
        ).distinct()
     
    paginator = Paginator(post_list, 3) #show 3 post per page

    page = request.GET.get('page')
    post_list = paginator.get_page(page)
    context = {
        'post_list' : post_list ,
    }
    
    return render(request , 'Post/post_list.html' , context)


def post_detail(request , id):
    post_detail = Post.objects.get(id=id)
    categories = Category.objects.all()
    all_tags = Tag.objects.all()
    comments = Comment.objects.filter(post=post_detail)
    comment_form = CommentForm()

    if request.method == 'POST' :
        comment_form = CommentForm(request.POST)
        if comment_form.is_valid():
            new_comment = comment_form.save(commit=False)
            new_comment.user = request.user
            new_comment.post = post_detail
            new_comment.save()

    else:
        comment_form = CommentForm()

    context = {
        'post_detail' : post_detail ,
        'categories' : categories ,
        'all_tags' : all_tags ,
        'comments' : comments ,
        'comment_form' : comment_form ,
    }

    return render(request , 'Post/post_detail.html' , context)


def post_by_tag(request , tag):
    post_by_tag = Post.objects.filter(tags__name__in=[tag])
    context = {
        'post_list' : post_by_tag ,
    }

    return render(request , 'Post/post_list.html' , context)


def post_by_category(request , category):
    post_by_category = Post.objects.filter(category__category_name    =category)
    context = {
        'post_list' : post_by_category ,
    }

    return render(request , 'Post/post_list.html' , context)

home/views.py
from django.shortcuts import render
from blog.models import Post
from .models import AboutUs , Services , Team , Testimony, Gallery, Application

# Create your views here.

def home(request):

    about = AboutUs.objects.all()
    services = Services.objects.all()
    team = Team.objects.all()
    testimony = Testimony.objects.all()
    gallery = Gallery.objects.all()
    application = Application.objects.all()
    posts = Post.objects.all().order_by('-created')
    latest_post = Post.objects.last()

    context = {  
        'about' : about ,
        'services' : services ,
        'team' : team ,
        'testimony' : testimony ,
        'gallery' : gallery ,
        'application' : application ,
        'posts' : posts ,
        'latest_post' : latest_post ,
    }

    return render(request , 'home/index.html' , context)

blog/templates/Post/post_detail.html
{% load static %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">

<!-- Mirrored from preview.colorlib.com/theme/unica/blog.html by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 05 Dec 2020 09:28:47 GMT -->
<head>
	<title>Divine Montessori Pre-School</title>
	<meta charset="UTF-8">
	<meta name="description" content="Unica University Template">
	<meta name="keywords" content="event, unica, creative, html">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Favicon -->   
	<link href="img/favicon.ico" rel="shortcut icon"/>

	<!-- Google Fonts -->
	<link href="https://fonts.googleapis.com/css?family=Rubik:400,400i,500,500i,700,700i" rel="stylesheet">

	<!-- Stylesheets -->
	<link rel="stylesheet" href="{% static 'new/css/bootstrap.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'new/css/font-awesome.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'new/css/themify-icons.css' %}"/>
	<link rel="stylesheet" href="{% static 'new/css/owl.carousel.css' %}"/>
	<link rel="stylesheet" href="{% static 'new/css/style.css' %}"/>


	<!--[if lt IE 9]>
	  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->

</head>
<body>
	<!-- Page Preloder -->
	<div id="preloder">
		<div class="loader"></div>
	</div>

	
	<!-- header section -->
	<header class="header-section">
		<div class="container">
			<!-- logo -->
			<a href="/" class="site-logo"><img src="{% static 'new/img/logo.png' %}" alt=""></a>
			<div class="nav-switch">
				<i class="fa fa-bars"></i>
			</div>
			<div class="header-info">
                <div class="hf-item">
                    <li><a href="https://wa.me/?text=I'm%20inquiring%20about%20divine%20montessori%20pre-school%20enrollments/<+27834269671/"><i class="fa fa-whatsapp"></i> WhatsApp US</a></li>					
				</div>
				<div class="hf-item">
                    <li><a href="tel:+27834269671"><i class="fa fa-phone"></i> Click To Call</a></li>			
				</div>
				<div class="hf-item">
                    <li><a href=""><i class="fa fa-map-marker"></i> 123 Umgawu Street, Bircharcers</a></li>			
				</div>
			</div>
		</div>
	</header>
	<!-- header section end-->


	<!-- Header section  -->
	<nav class="nav-section">
		<div class="container">
			<div class="nav-right">
				<a href="https://wa.me/?text=I'm%20inquiring%20about%20divine%20montessori%20pre-school%20enrollments/<+27834269671/"><i class="fa fa-whatsapp"></i> WhatsApp US</a>
				<a href="tel:+27834269671"><i class="fa fa-phone"></i> Click To Call</a>
			</div>
			<ul class="main-menu">
				<li><a href="/">Home</a></li>
				<li class="active"><a href="{% url 'blog:post_list' %}">blog</a></li>
			</ul>
		</div>
	</nav>
<hr><br><br><br>
	<!-- Blog page section  -->
	<section class="blog-page-section spad pt-0">
		<div class="container">
			<div class="row">
				<div class="col-md-8">
					<div class="post-item post-details">
						<img src="{{post_detail.image.url}}" class="post-thumb-full" alt="">
						<div class="post-content">
							<h3><a href="single-blog.html">{{post_detail}}</a></h3>
							<div class="post-meta">
								<span><i class="fa fa-calendar-o"></i> {{post_detail.created}}</span>
								<span><i class="fa fa-user"></i>  {{post_detail.author}}</span>
								<span><i class="fa fa-group"></i> In {{post_detail.category}} Category</span>
							</div>
							
							<blockquote>{{post_detail.content|safe}}</blockquote>
							
								<div class="tag">Tags:
								{% for tag in post_detail.tags.all %}
									<i class="fa fa-tag"></i>  {{tag.name}} |
								{% endfor %}
								</div>
							
						</div>
						
						<div class="comment-warp">
							<h4 class="comment-title">Comments</h4>
							<ul class="comment-list">
								<li>
									{% for comment in comments  %}
										<div class="comment">
											<div class="comment-avator set-bg" data-setbg="{% static 'new/img/blog/comment/1.jpg' %}"></div>
											
												<div class="comment-content">
													<span class="c-date">{{comment.created}}</span>
													<h5>{{comment.user}}</h5>
													<p>{{comment.content}}</p>
													
												</div>
											
										</div>
									{% endfor %}
								</li>
								
							</ul>
						<br><br><hr>
							<div class="comment-form-warp">
								
								<div class="comment-form-wrap pt-5">
									<h3 class="mb-5">Leave a comment</h3>
									<form method="POST" class="p-5 bg-light">
										{% csrf_token %}
										{% bootstrap_form comment_form %}
										{% buttons %}
											<button type="submit" class="btn btn-primary">Leave A Comment</button>
										{% endbuttons %}
									</form>
								  </div>
							</div>
						</div>
					</div>
				</div>
				<!-- sidebar -->
				<div class="col-sm-8 col-md-5 col-lg-4 col-xl-3 offset-xl-1 offset-0 pl-xl-0 sidebar">
					<!-- widget -->
					<div class="widget">
						<form action=" {% url 'blog:post_list' %}" method="GET" class="search-widget">
							<input type="text" class="form-control" name='q' value="{{request.GET.q}}" placeholder="Search...">
							<button><i class="ti-search"></i></button>
						</form>
					</div>
					<!-- widget -->
					<div class="widget">
						<h4 class="widget-title">Tags</h4>
						<div class="tags">
							{% for tag in all_tags  %}
							<a href="{% url 'blog:post_by_tag' tag %}">{{tag}}</a>
							{% endfor %}
							
						</div>
					</div>
					<!-- widget -->
					<div class="widget">
						<h4 class="widget-title">Categories</h4>
						{% for category in categories  %}
						<ul>
							<li><a href="#">{{category}}</a></li>
							
						</ul>
						{% endfor %}
					</div>
			
				</div>
			</div>
		</div>
	</section>
	<!-- Blog page section end -->

	<!-- Footer section -->
	<footer class="footer-section">
		<div class="container footer-top">
			<div class="row">
				<!-- widget -->
				<div class="col-sm-6 col-lg-3 footer-widget">
					<div class="about-widget">
						<img src="img/logo-light.png" alt="">
						<p>Let's go social, here is where to connect with us:</p>
						<div class="social pt-1">
							<a href="#"><i class="fa fa-twitter-square"></i></a>
							<a href="#"><i class="fa fa-facebook-square"></i></a>
							<a href="#"><i class="fa fa-google-plus-square"></i></a>
							<a href="#"><i class="fa fa-linkedin-square"></i></a>
							<a href="#"><i class="fa fa-rss-square"></i></a>
						</div>
					</div>
				</div>
				<!-- widget -->
				<div class="col-sm-6 col-lg-3 footer-widget">
					<h6 class="fw-title">USEFUL LINK</h6>
					<div class="dobule-link">
						<ul>
							<li><a href="#">Home</a></li>
							<li><a href="#">About us</a></li>
							<li><a href="#">Services</a></li>
							<li><a href="#">Events</a></li>
							<li><a href="#">Features</a></li>
						</ul>
						<ul>
							<li><a href="#">Policy</a></li>
							<li><a href="#">Term</a></li>
							<li><a href="#">Help</a></li>
							<li><a href="#">FAQs</a></li>
							<li><a href="#">Site map</a></li>
						</ul>
					</div>
				</div>
				<!-- widget -->
				<div class="col-sm-6 col-lg-3 footer-widget">
					<h6 class="fw-title"></h6>
					<ul class="recent-post">
						<li>
							<p><br> </p>
							<span><i class="fa fa-clock-o"></i></span>
						</li>
						<li>
							<p></p>
							<span><i class="fa fa-clock-o"></i></span>
						</li>
					</ul>
				</div>
				<!-- widget -->
				<div class="col-sm-6 col-lg-3 footer-widget">
					<h6 class="fw-title">CONTACT</h6>
					<ul class="contact">
						<li><p><i class="fa fa-map-marker"></i> 32/4244 Umgeya Street, Birch Acres</p></li>
						<li><p><i class="fa fa-phone"></i> +27834269671</p></li>
						<li><p><i class="fa fa-envelope"></i> divinemont@gmail.com</p></li>
						<li><p><i class="fa fa-clock-o"></i> Monday - Friday, 08:00AM - 06:00 PM</p></li>
					</ul>
				</div>
			</div>
		</div>
		<!-- copyright -->
		<div class="copyright">
			<div class="container">
				<p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Divine Montessori - Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://africaarisecoding.com/" target="_blank">AfricaAriseCoding.com</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
			</div>		
		</div>
	</footer>
	<!-- Footer section end-->


	<!--====== Javascripts & Jquery ======-->
	<script src="{% static 'new/js/jquery-3.2.1.min.js' %}"></script>
	<script src="{% static 'new/js/owl.carousel.min.js' %}"></script>
	<script src="{% static 'new/js/jquery.countdown.js' %}"></script>
	<script src="{% static 'new/js/masonry.pkgd.min.js' %}"></script>
	<script src="{% static 'new/js/magnific-popup.min.js' %}"></script>
	<script src="{% static 'new/js/main.js' %}"></script>

	<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-23581568-13');
</script>
	
</body>

<!-- Mirrored from preview.colorlib.com/theme/unica/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 05 Dec 2020 09:28:36 GMT -->
</html>

blog/templates/Post/post_list.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<!-- Mirrored from preview.colorlib.com/theme/unica/blog.html by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 05 Dec 2020 09:28:47 GMT -->
<head>
	<title>Divine Montessori Pre-School</title>
	<meta charset="UTF-8">
	<meta name="description" content="Unica University Template">
	<meta name="keywords" content="event, unica, creative, html">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
	<!-- Favicon -->   
	<link href="img/favicon.ico" rel="shortcut icon"/>

	<!-- Google Fonts -->
	<link href="https://fonts.googleapis.com/css?family=Rubik:400,400i,500,500i,700,700i" rel="stylesheet">

	<!-- Stylesheets -->
	<link rel="stylesheet" href="{% static 'new/css/bootstrap.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'new/css/font-awesome.min.css' %}"/>
	<link rel="stylesheet" href="{% static 'new/css/themify-icons.css' %}"/>
	<link rel="stylesheet" href="{% static 'new/css/owl.carousel.css' %}"/>
	<link rel="stylesheet" href="{% static 'new/css/style.css' %}"/>


	<!--[if lt IE 9]>
	  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->

</head>
<body>
	<!-- Page Preloder -->
	<div id="preloder">
		<div class="loader"></div>
	</div>

	
	<!-- header section -->
	<header class="header-section">
		<div class="container">
			<!-- logo -->
			<a href="/" class="site-logo"><img src="{% static 'new/img/logo.png' %}" alt=""></a>
			<div class="nav-switch">
				<i class="fa fa-bars"></i>
			</div>
			<div class="header-info">
                <div class="hf-item">
                    <li><a href="https://wa.me/?text=I'm%20inquiring%20about%20divine%20montessori%20pre-school%20enrollments/<+27834269671/"><i class="fa fa-whatsapp"></i> WhatsApp US</a></li>					
				</div>
				<div class="hf-item">
                    <li><a href="tel:+27834269671"><i class="fa fa-phone"></i> Click To Call</a></li>			
				</div>
				<div class="hf-item">
                    <li><a href=""><i class="fa fa-map-marker"></i> 123 Umgawu Street, Bircharcers</a></li>			
				</div>
			</div>
		</div>
	</header>
	<!-- header section end-->


	<!-- Header section  -->
	<nav class="nav-section">
		<div class="container">
			<div class="nav-right">
				<a href="https://wa.me/?text=I'm%20inquiring%20about%20divine%20montessori%20pre-school%20enrollments/<+27834269671/"><i class="fa fa-whatsapp"></i> WhatsApp US</a>
				<a href="tel:+27834269671"><i class="fa fa-phone"></i> Click To Call</a>
			</div>
			<ul class="main-menu">
				<li><a href="/">Home</a></li>
				<li class="active"><a href="{% url 'blog:post_list' %}">blog</a></li>
			</ul>
		</div>
	</nav>
	<!-- Header section end -->
<hr><br><br><br>
	<!-- Blog page section  -->
	<section class="blog-page-section spad pt-0">
		<div class="container">
			<div class="row">
				<div class="col-lg-8 post-list">
					{% for post in post_list %}
						<div class="post-item">
							<a href="{% url 'blog:post_detail' post.id %}"></a><div class="post-thumb set-bg" data-setbg="{{post.image.url}}"></div></a>
							<div class="post-content">
								<h3><a href="{% url 'blog:post_detail' post.id %}">{{post}}</a></h3>
								<div class="post-meta">
									<span><i class="fa fa-calendar-o"></i> {{post.created}}</span>
									<span><i class="fa fa-user"></i> {{post.author}}</span>
								</div>
								<p>{{post.content|safe|truncatewords:25}}</p>
							</div>
							<br>
							<p><a href="{% url 'blog:post_detail' post.id %}" class="btn btn-primary btn-outline-primary btn-sm">Read
								More</a></p>
						</div>
						<hr>
					{% endfor %}

					<ul class="site-pageination">
						{% if post_list.has_other_pages %}
							{% if post_list.has_previous %}
								<li><a href="?page={{post_list.previous_page_number}}"><i class="fa fa-angle-left"></i></a></li>
							{% else %}
								<li class="disabled"></li>
							  {% endif %}
							{% for pages in post_list.paginator.page_range %}
							  {% if post_list.number == pages %}
								<li><a href="#" class="active">{{pages}}</a></li>
								{% else %}
								<li class="page-item active"><a class="page-linkx" href="?page={{pages}}">{{pages}}</a></li>
							  {% endif %}
							  
							{% endfor %}
							{% if post_list.has_next %}
								<li><a href="?page={{post_list.next_page_number}}"><i class="fa fa-angle-right"></i></a></li>
								{% else %}
								<li class="disabled"></li>
							{% endif %} 
						{% endif %}
					</ul>

				</div>
				<!-- sidebar -->
				<div class="col-sm-8 col-md-5 col-lg-4 col-xl-3 offset-xl-1 offset-0 pl-xl-0 sidebar">
					<!-- widget -->
					<div class="widget">
						<form action=" {% url 'blog:post_list' %}" method="GET" class="search-widget">
							<input type="text" class="form-control" name='q' value="{{request.GET.q}}" placeholder="Search...">
							<button><i class="ti-search"></i></button>
						</form>
					</div>
			
				</div>
			</div>
		</div>
	</section>
	<!-- Blog page section end -->

<!-- Footer section -->
<footer class="footer-section">
	<div class="container footer-top">
		<div class="row">
			<!-- widget -->
			<div class="col-sm-6 col-lg-3 footer-widget">
				<div class="about-widget">
					<img src="img/logo-light.png" alt="">
					<p>Let's go social, here is where to connect with us:</p>
					<div class="social pt-1">
						<a href="#"><i class="fa fa-twitter-square"></i></a>
						<a href="#"><i class="fa fa-facebook-square"></i></a>
						<a href="#"><i class="fa fa-google-plus-square"></i></a>
						<a href="#"><i class="fa fa-linkedin-square"></i></a>
						<a href="#"><i class="fa fa-rss-square"></i></a>
					</div>
				</div>
			</div>
			<!-- widget -->
			<div class="col-sm-6 col-lg-3 footer-widget">
				<h6 class="fw-title">USEFUL LINK</h6>
				<div class="dobule-link">
					<ul>
						<li><a href="#">Home</a></li>
						<li><a href="#">About us</a></li>
						<li><a href="#">Services</a></li>
						<li><a href="#">Events</a></li>
						<li><a href="#">Features</a></li>
					</ul>
					<ul>
						<li><a href="#">Policy</a></li>
						<li><a href="#">Term</a></li>
						<li><a href="#">Help</a></li>
						<li><a href="#">FAQs</a></li>
						<li><a href="#">Site map</a></li>
					</ul>
				</div>
			</div>
			<!-- widget -->
			<div class="col-sm-6 col-lg-3 footer-widget">
				<h6 class="fw-title"></h6>
				<ul class="recent-post">
					<li>
						<p><br> </p>
						<span><i class="fa fa-clock-o"></i></span>
					</li>
					<li>
						<p></p>
						<span><i class="fa fa-clock-o"></i></span>
					</li>
				</ul>
			</div>
			<!-- widget -->
			<div class="col-sm-6 col-lg-3 footer-widget">
				<h6 class="fw-title">CONTACT</h6>
				<ul class="contact">
					<li><p><i class="fa fa-map-marker"></i> 32/4244 Umgeya Street, Birch Acres</p></li>
					<li><p><i class="fa fa-phone"></i> +27834269671</p></li>
					<li><p><i class="fa fa-envelope"></i> divinemont@gmail.com</p></li>
					<li><p><i class="fa fa-clock-o"></i> Monday - Friday, 08:00AM - 06:00 PM</p></li>
				</ul>
			</div>
		</div>
	</div>
	<!-- copyright -->
	<div class="copyright">
		<div class="container">
			<p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Divine Montessori - Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="fa fa-heart-o" aria-hidden="true"></i> by <a href="https://africaarisecoding.com/" target="_blank">AfricaAriseCoding.com</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></p>
		</div>		
	</div>
</footer>
<!-- Footer section end-->


<!--====== Javascripts & Jquery ======-->
<script src="{% static 'new/js/jquery-3.2.1.min.js' %}"></script>
<script src="{% static 'new/js/owl.carousel.min.js' %}"></script>
<script src="{% static 'new/js/jquery.countdown.js' %}"></script>
<script src="{% static 'new/js/masonry.pkgd.min.js' %}"></script>
<script src="{% static 'new/js/magnific-popup.min.js' %}"></script>
<script src="{% static 'new/js/main.js' %}"></script>

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-23581568-13');
</script>

</body>

<!-- Mirrored from preview.colorlib.com/theme/unica/index.html by HTTrack Website Copier/3.x [XR&CO'2014], Sat, 05 Dec 2020 09:28:36 GMT -->
</html>